export type CategoryId = "all" | "pdf" | "img" | "video" | "audio" | "doc" | "ai" | "code";

export type Tool = {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: Exclude<CategoryId, "all">;
  popular?: boolean;
  soon?: boolean;
  isNew?: boolean;
};

export const CATEGORIES: { id: CategoryId; label: string; emoji: string }[] = [
  { id: "all",   label: "All tools",    emoji: "⚡" },
  { id: "pdf",   label: "PDF Tools",    emoji: "📄" },
  { id: "img",   label: "Image Tools",  emoji: "🖼️" },
  { id: "video", label: "Video Tools",  emoji: "🎬" },
  { id: "audio", label: "Audio Tools",  emoji: "🎵" },
  { id: "doc",   label: "Doc Tools",    emoji: "📝" },
  { id: "ai",    label: "AI Tools",     emoji: "🤖" },
  { id: "code",  label: "Code Tools",   emoji: "🐍" },
];

export const CAT_LABEL: Record<CategoryId, string> = {
  all:   "All",
  pdf:   "PDF",
  img:   "Image",
  video: "Video",
  audio: "Audio",
  doc:   "Doc",
  ai:    "AI",
  code:  "Code",
};

export const TOOLS: Tool[] = [
  { id: "merge-pdf",        name: "Merge PDF",          icon: "🔗", description: "Combine multiple PDF files into one document in seconds.",                    category: "pdf", popular: true  },
  { id: "split-pdf",        name: "Split PDF",           icon: "✂️", description: "Extract pages or split a PDF into multiple separate files.",                  category: "pdf", popular: true  },
  { id: "compress-pdf",     name: "Compress PDF",        icon: "📦", description: "Reduce PDF file size while keeping the best possible quality.",               category: "pdf", popular: true  },
  { id: "pdf-to-jpg",       name: "PDF to JPG",          icon: "🖼️", description: "Convert every PDF page into a high-quality JPG image.",                       category: "pdf"                },
  { id: "jpg-to-pdf",       name: "JPG to PDF",          icon: "📎", description: "Turn one or more images into a single PDF document.",                         category: "pdf"                },
  { id: "rotate-pdf",       name: "Rotate PDF",          icon: "🔄", description: "Fix page orientation — rotate any page to the right angle.",                  category: "pdf"                },
  { id: "watermark-pdf",    name: "Watermark PDF",       icon: "💧", description: "Stamp a custom text or image watermark on every page.",                       category: "pdf"                },
  { id: "protect-pdf",      name: "Protect PDF",         icon: "🔒", description: "Lock your PDF with a password to keep it private.",                          category: "pdf"                },
  { id: "unlock-pdf",       name: "Unlock PDF",          icon: "🔓", description: "Remove the password from a PDF you own.",                                     category: "pdf"                },
  { id: "reorder-pdf",      name: "Reorder Pages",       icon: "🗂️", description: "Drag and drop pages to rearrange them in any order.",                         category: "pdf", isNew: true    },
  { id: "pdf-to-text",      name: "PDF to Text",         icon: "📝", description: "Extract all text content from your PDF.",                                   category: "pdf", isNew: true    },
  { id: "pdf-grayscale",    name: "PDF Grayscale",       icon: "🔘", description: "Convert a color PDF to black & white.",                                     category: "pdf", isNew: true    },
  { id: "add-page-numbers", name: "Add Page Numbers",    icon: "🔢", description: "Stamp page numbers on every page of your PDF.",                             category: "pdf", isNew: true    },
  { id: "pdf-metadata",     name: "PDF Metadata",        icon: "🏷️", description: "View and edit PDF title, author, subject and keywords.",                    category: "pdf", isNew: true    },
  { id: "pdf-to-word",       name: "PDF to Word",         icon: "📝", description: "Convert PDF to editable Word (.docx) document in your browser.",              category: "pdf", isNew: true, popular: true },
  { id: "pdf-to-excel",      name: "PDF to Excel",        icon: "📊", description: "Extract tables and text from PDF into an Excel spreadsheet.",                   category: "pdf", isNew: true },
  { id: "delete-pdf-pages",  name: "Delete PDF Pages",    icon: "🗑️", description: "Remove specific pages from a PDF quickly and easily.",                          category: "pdf", isNew: true },
  { id: "extract-pdf-images",name: "Extract PDF Images",  icon: "🖼️", description: "Pull out all embedded images from a PDF as downloadable JPG files.",            category: "pdf", isNew: true },
  { id: "pdf-to-html",       name: "PDF to HTML",         icon: "🌐", description: "Convert PDF pages to clean HTML — open in any browser.",                        category: "pdf", isNew: true },
  { id: "crop-pdf",          name: "Crop PDF Pages",      icon: "✂️", description: "Trim margins and crop pages to a custom size.",                                 category: "pdf", isNew: true },
  { id: "flatten-pdf",       name: "Flatten PDF",         icon: "📋", description: "Flatten form fields and annotations into the page permanently.",                 category: "pdf", isNew: true },
  { id: "pdf-sign",          name: "Sign PDF",            icon: "✍️", description: "Draw your signature and embed it anywhere on a PDF page.",                      category: "pdf", isNew: true, popular: true },
  { id: "pdf-redact",        name: "PDF Redactor",        icon: "⬛", description: "Black out sensitive text and information permanently from PDFs.",                category: "pdf", isNew: true },
  { id: "word-to-pdf",       name: "Word to PDF",         icon: "📄", description: "Convert .docx Word documents to PDF — 100% in browser.",                       category: "pdf", isNew: true, popular: true },
  { id: "pdf-repair",        name: "PDF Repair",          icon: "🔧", description: "Attempt to fix and recover corrupted or damaged PDF files.",                    category: "pdf", isNew: true },
  { id: "compress-image",   name: "Compress Image",      icon: "🗜️", description: "Reduce image file size with smart quality control.",                         category: "img", popular: true, isNew: true },
  { id: "resize-image",     name: "Resize Image",        icon: "📐", description: "Resize images to exact dimensions or by percentage.",                        category: "img", popular: true, isNew: true },
  { id: "convert-image",    name: "Convert Image",       icon: "🔄", description: "Convert between JPG, PNG, WebP, BMP, GIF and more.",                        category: "img", isNew: true },
  { id: "rotate-image",     name: "Rotate & Flip",       icon: "↩️", description: "Rotate images and flip them horizontally or vertically.",                    category: "img", isNew: true },
  { id: "crop-image",       name: "Crop Image",          icon: "✂️", description: "Crop images to the exact size you need.",                                   category: "img", isNew: true },
  { id: "watermark-image",  name: "Watermark Image",     icon: "💧", description: "Add a text watermark to protect your images.",                              category: "img", isNew: true },
  { id: "compress-video",   name: "Compress Video",      icon: "📦", description: "Reduce video file size while preserving quality.",                           category: "video", popular: true, isNew: true },
  { id: "convert-video",    name: "Convert Video",       icon: "🔄", description: "Convert between MP4, WebM, AVI, MOV and more.",                             category: "video", popular: true, isNew: true },
  { id: "trim-video",       name: "Trim Video",          icon: "✂️", description: "Cut your video — set a start and end point to keep only what you need.",    category: "video", popular: true, isNew: true },
  { id: "extract-audio",    name: "Extract Audio",       icon: "🎵", description: "Pull the audio track from any video as MP3, WAV or AAC.",                   category: "video", isNew: true },
  { id: "video-to-gif",     name: "Video to GIF",        icon: "🎞️", description: "Convert a short video clip into an animated GIF with live preview.",        category: "video", isNew: true, popular: true },
  { id: "mute-video",       name: "Mute Video",          icon: "🔇", description: "Remove the audio track from a video completely.",                            category: "video", isNew: true },
  { id: "rotate-video",     name: "Rotate Video",        icon: "↩️", description: "Rotate or flip a video in any direction.",                                  category: "video", isNew: true },
  { id: "subtitle-generator", name: "Subtitle Generator", icon: "💬", description: "Auto-generate subtitles from any video or audio file.", category: "video", popular: true, isNew: true },
  { id: "video-speed",      name: "Video Speed Changer", icon: "⚡", description: "Speed up or slow down any video from 0.25x to 4x.",                         category: "video", isNew: true, popular: true },
  { id: "video-reverse",    name: "Reverse Video",       icon: "⏪", description: "Play your video backwards — the reverse effect.",                            category: "video", isNew: true, popular: true },
  { id: "video-boomerang",  name: "Boomerang Video",     icon: "🪃", description: "Create an Instagram-style boomerang — forward then backward loop.",         category: "video", isNew: true, popular: true },
  { id: "video-crop",       name: "Crop Video",          icon: "✂️", description: "Crop video to 1:1, 16:9, 9:16, or 4:3 aspect ratio.",                       category: "video", isNew: true },
  { id: "video-filter",     name: "Video Color Filter",  icon: "🎨", description: "Apply grayscale, sepia, vintage, vivid, cool or warm filters to video.",    category: "video", isNew: true, popular: true },
  { id: "add-audio",        name: "Add Audio to Video",  icon: "🔊", description: "Replace or add an audio track to any silent or existing video.",            category: "video", isNew: true },
  { id: "video-thumbnail",  name: "Video Thumbnail",     icon: "🖼️", description: "Extract any frame from a video as a high-quality JPEG image.",              category: "video", isNew: true },
  { id: "gif-to-mp4",       name: "GIF to MP4",          icon: "🎬", description: "Convert an animated GIF into a compact, shareable MP4 video.",              category: "video", isNew: true },
  { id: "video-loop",       name: "Loop Video",          icon: "🔁", description: "Repeat a video clip 2–10 times and merge into one file.",                   category: "video", isNew: true },
  { id: "video-watermark-text", name: "Burn Text on Video", icon: "🖊️", description: "Permanently burn custom text into your video frames.",                  category: "video", isNew: true },
  { id: "audio-trim",       name: "Trim Audio",          icon: "✂️", description: "Cut your audio — set start and end points to keep exactly what you need.",  category: "audio", isNew: true, popular: true },
  { id: "audio-convert",    name: "Convert Audio",       icon: "🔄", description: "Convert between MP3, WAV, AAC, OGG, FLAC and M4A formats.",                 category: "audio", isNew: true, popular: true },
  { id: "audio-volume",     name: "Adjust Volume",       icon: "🔊", description: "Boost or reduce audio volume by any amount.",                                category: "audio", isNew: true },
  { id: "audio-speed",      name: "Audio Speed Changer", icon: "⚡", description: "Speed up or slow down audio without changing the pitch.",                    category: "audio", isNew: true, popular: true },
  { id: "audio-reverse",    name: "Reverse Audio",       icon: "⏪", description: "Play audio backwards — great for creative effects.",                         category: "audio", isNew: true },
  { id: "audio-merge",      name: "Merge Audio Files",   icon: "🔗", description: "Concatenate multiple audio files into a single MP3.",                       category: "audio", isNew: true, popular: true },
  { id: "audio-fade",       name: "Audio Fade In/Out",   icon: "🌊", description: "Add professional fade in and fade out effects to any audio file.",           category: "audio", isNew: true },
  { id: "audio-normalize",  name: "Normalize Audio",     icon: "📊", description: "Auto-balance audio loudness to a consistent professional level.",            category: "audio", isNew: true },
  { id: "audio-remove-silence", name: "Remove Silence",  icon: "🤫", description: "Automatically detect and remove silent gaps from audio.",                   category: "audio", isNew: true },
  { id: "audio-to-video",   name: "Audio to Video",      icon: "🎞️", description: "Combine audio with a cover image to create a shareable MP4 video.",         category: "audio", isNew: true, popular: true },
  { id: "markdown-to-html",  name: "Markdown to HTML",   icon: "🌐", description: "Convert a Markdown file or text into a clean, standalone HTML document.",               category: "doc", isNew: true },
  { id: "html-to-markdown",  name: "HTML to Markdown",   icon: "⬇️", description: "Strip HTML and turn any webpage or HTML file into readable Markdown.",                   category: "doc", isNew: true },
  { id: "markdown-to-word",  name: "Markdown to Word",   icon: "📄", description: "Turn Markdown text into a formatted .docx Word document instantly.",                      category: "doc", isNew: true, popular: true },
  { id: "word-to-markdown",  name: "Word to Markdown",   icon: "🔄", description: "Upload a .docx file and get clean Markdown text back.",                                   category: "doc", isNew: true },
  { id: "html-to-word",      name: "HTML to Word",       icon: "📎", description: "Convert HTML content into a downloadable .docx Word document.",                          category: "doc", isNew: true },
  { id: "word-to-html",      name: "Word to HTML",       icon: "🌐", description: "Convert a .docx Word document into a standalone HTML file.",                             category: "doc", isNew: true },
  { id: "background-remover",  name: "Background Remover",   icon: "✂️", description: "Remove image backgrounds instantly with AI — no signup, no upload, 100% private.", category: "ai", isNew: true, popular: true },
  { id: "face-blur",           name: "Face Blur",             icon: "😶", description: "Auto-detect and blur faces in photos to protect privacy. AI-powered, browser-only.", category: "ai", isNew: true, popular: true },
  { id: "passport-photo",      name: "Passport Photo Maker",  icon: "🪪", description: "Turn any photo into a passport-size photo with white or blue background.", category: "ai", isNew: true, popular: true },
  { id: "image-upscaler",      name: "AI Image Upscaler",     icon: "🔍", description: "Enlarge and enhance images 2x or 4x with AI super resolution.", category: "ai", isNew: true, popular: true },
  { id: "image-caption",       name: "AI Image Caption",      icon: "💬", description: "Automatically describe any image using AI in seconds.", category: "ai", isNew: true },
  { id: "ai-summarizer",       name: "AI Text Summarizer",    icon: "📋", description: "Paste any long text and get a concise AI-generated summary instantly.", category: "ai", isNew: true, popular: true },
  { id: "sentiment-analyzer",  name: "Sentiment Analyzer",    icon: "😊", description: "Detect the sentiment of any text — positive, negative or neutral.", category: "ai", isNew: true },
  { id: "language-detector",   name: "Language Detector",     icon: "🌍", description: "Identify the language of any text instantly using AI.", category: "ai", isNew: true },
  { id: "object-detector",     name: "Object Detector",       icon: "🎯", description: "Detect and label all objects in a photo with bounding boxes.", category: "ai", isNew: true, popular: true },
  { id: "ai-grammar",          name: "AI Grammar Fixer",      icon: "✍️", description: "Fix grammar, spelling and punctuation mistakes with AI.", category: "ai", isNew: true },
  { id: "pdf-password-remover", name: "PDF Password Remover",  icon: "🔐", description: "Remove password protection from PDF files — 100% private, browser-only.", category: "ai", isNew: true },
  { id: "image-ocr",            name: "Image to Text (OCR)",   icon: "📄", description: "Extract text from images using Tesseract.js WASM OCR.", category: "ai", isNew: true, popular: true },
  { id: "qr-generator",         name: "QR Code Generator",     icon: "📱", description: "Generate QR codes for URLs, text, contacts instantly.", category: "ai", isNew: true, popular: true },
  { id: "qr-scanner",           name: "QR Code Scanner",       icon: "📷", description: "Scan and decode QR codes from images.", category: "ai", isNew: true },
  { id: "image-to-webp",        name: "Image to WebP/AVIF",    icon: "🖼️", description: "Convert images to modern WebP or AVIF format in browser.", category: "ai", isNew: true },
  { id: "e-signature",          name: "E-Signature Maker",     icon: "✍️", description: "Draw and export your digital signature as PNG.", category: "ai", isNew: true },
  // ── Code / Developer tools ───────────────────────────────────────────────
  { id: "python-playground",   name: "Python Playground",     icon: "🐍", description: "Run Python code right in your browser — no install, no server, 100% private.", category: "code", isNew: true, popular: true },
  { id: "csv-analyzer",        name: "CSV Analyzer",          icon: "📊", description: "Upload a CSV file and get instant statistics, preview, and per-column analysis with Python.", category: "code", isNew: true, popular: true },
  { id: "regex-tester",        name: "Regex Tester",          icon: "🔎", description: "Test Python regular expressions with live match highlighting and group details.", category: "code", isNew: true },
  { id: "hash-generator",      name: "Hash Generator",        icon: "🔐", description: "Generate MD5, SHA-1, SHA-256 and SHA-512 hashes from text or a file using Python.", category: "code", isNew: true },
];
